### ISSUE TITLE
Frontend Monitor Webserver does not run

### ISSUE THREAD

**Issue by Sonblind** [javahippie/geth-dev#10]
**Describe the bug**
`localhost:3000` cannot be reached. Geth connection in console is also refused.

**To Reproduce**
1. Go to root of project folder
2. Run `docker-compose up`
3. Visit `localhost:3000` in the browser & run `geth attach http://localhost:8545` in the command line.
4. See browser error: "This site can’t be reached... localhost refused to connect.", and "connection refused" error in the command line for geth.

**Expected behavior**
The web page should load and render a page. I should be able to connect through geth in the console with `geth attach http://localhost:8545`.

**Screenshots**

Docker logs shows: 
```
geth-miner-2             | DEBUG[07-28|00:43:48.489] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:43:48.529] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
monitor-backend          | 2018-07-28 00:42 +00:00: [eth] =i= { id: 'gethDev1',
monitor-backend          |   stats:
monitor-backend          |    { active: true,
monitor-backend          |      syncing: false,
monitor-backend          |      mining: true,
monitor-backend          |      hashrate: 0,
monitor-backend          |      peers: 2,
monitor-backend          |      gasPrice: '18000000000',
monitor-backend          |      uptime: 100 } }
monitor-frontend         | 2018-07-28 00:42:09.406 [API] [STA] Stats from: gethDev1
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =✘= TypeError: results.reverse is not a function
monitor-backend          |     at /opt/eth-net-intelligence-api/lib/node.js:622:21
monitor-backend          |     at /opt/eth-net-intelligence-api/node_modules/async/lib/async.js:52:16
monitor-backend          |     at /opt/eth-net-intelligence-api/node_modules/async/lib/async.js:361:13
monitor-backend          |     at /opt/eth-net-intelligence-api/node_modules/async/lib/async.js:52:16
monitor-backend          |     at iterate (/opt/eth-net-intelligence-api/node_modules/async/lib/async.js:260:24)
monitor-backend          |     at async.forEachOfSeries.async.eachOfSeries (/opt/eth-net-intelligence-api/node_modules/async/lib/async.js:281:9)
monitor-backend          |     at _asyncMap (/opt/eth-net-intelligence-api/node_modules/async/lib/async.js:355:9)
monitor-backend          |     at Object.mapSeries (/opt/eth-net-intelligence-api/node_modules/async/lib/async.js:347:20)
monitor-backend          |     at Node.getHistory (/opt/eth-net-intelligence-api/lib/node.js:601:8)
monitor-backend          |     at Primus.<anonymous> (/opt/eth-net-intelligence-api/lib/node.js:246:8)
monitor-backend          | [2018-07-28T00:44:09.448Z] PM2 log: App [geth-dev-1] with id [1] and pid [288], exited with code [1] via signal [SIGINT]
monitor-backend          | [2018-07-28T00:44:09.450Z] PM2 log: Starting execution sequence in -fork mode- for app name:geth-dev-1 id:1
monitor-backend          | [2018-07-28T00:44:09.453Z] PM2 log: App name:geth-dev-1 id:1 online
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]     NET STATS CLIENT
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]     v0.1.1
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =i= Starting web3 connection
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =✓= Web3 connection established
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] ==> Getting info
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =i= { name: 'geth-dev-1',
monitor-backend          |   contact: '',
monitor-backend          |   coinbase: '0x3590aca93338b0721966a8d0c96ebf2c4c87c544',
monitor-backend          |   node: 'Geth/v1.8.12-stable-37685930/linux-amd64/go1.10.3',
monitor-backend          |   net: '500',
monitor-backend          |   protocol: 63,
monitor-backend          |   api: '0.15.3',
monitor-backend          |   port: 30303,
monitor-backend          |   os: 'linux',
monitor-backend          |   os_v: '4.4.74-boot2docker',
monitor-backend          |   client: '0.1.1',
monitor-backend          |   canUpdateHistory: true }
monitor-backend          | 2018-07-28 00:44 +00:00: [wsc] =i= Starting socket connection
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =✓= Installed chain filter
monitor-frontend         | 2018-07-28 00:44:09.446 [API] [CON] Connection with: MJULUXH ended: undefined
monitor-backend          | 2018-07-28 00:44 +00:00: [eth] =✓= Installed pending filter
monitor-backend          | 2018-07-28 00:44 +00:00: [wsc] =i= The socket connection has been opened.
monitor-backend          | 2018-07-28 00:44 +00:00: [eth]     Trying to login
monitor-frontend         | 2018-07-28 00:44:11.130 [API] [CON] Connected gethDev1
monitor-backend          | 2018-07-28 00:44 +00:00: [wsc] =✓= The socket connection has been established.
monitor-frontend         | 2018-07-28 00:44:11.148 [API] [BLK] Block: 1 from: gethDev1
geth-miner-3             | DEBUG[07-28|00:44:08.480] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-2             | DEBUG[07-28|00:44:08.489] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:44:08.529] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-3             | DEBUG[07-28|00:44:28.480] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-2             | DEBUG[07-28|00:44:28.490] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:44:28.530] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-3             | DEBUG[07-28|00:44:48.481] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-2             | DEBUG[07-28|00:44:48.491] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:44:48.530] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-3             | DEBUG[07-28|00:45:08.481] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-2             | DEBUG[07-28|00:45:08.491] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:45:08.531] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-3             | DEBUG[07-28|00:45:28.481] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-2             | DEBUG[07-28|00:45:28.492] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
geth-miner-1             | DEBUG[07-28|00:45:28.531] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
```

Geth error:
```
 geth attach http://localhost:8545
Fatal: Failed to start the JavaScript console: api modules: Post http://localhost:8545: dial tcp [::1]:8545: connect: connection refused
```

**Desktop (please complete the following information):**
 - OS: OSX 10.13.5
 - Browser: Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)
 - Docker: 

```
Client:
 Version:           18.06.0-ce
 API version:       1.30 (downgraded from 1.38)
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          17.06.0-ce
  API version:      1.30 (minimum version 1.12)
  Go version:       go1.8.3
  Git commit:       02c1d87
  Built:            Fri Jun 23 21:51:55 2017
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by javahippie** [comment]
Hi Sam,

Thank you for your detailed report! I understand that you are also not able to connect with the geth console from your Mac, is this correct? In the logs, the monitor backend states that it is able to establish a web3 connection, so I am assuming the connectivity in your network is as expected, but there is a problem with accessing the docker network from your machine. 

Can you validate if the geth nodes are able to talk to each other via docker exec?

`docker exec $(docker inspect --format="{{.Id}}" geth-miner-1) /opt/geth attach http://docker inspect --format='{{index .NetworkSettings.Networks "geth-dev_chainnet" "IPAMConfig" "IPv4Address"}}' geth-miner-2:8545`

**Comment by Sonblind** [comment]
Hi @javahippie. Thanks for the fast reply. I ran that command and go this.

```
The Geth console is an interactive shell for the JavaScript runtime environment
which exposes a node admin interface as well as the Ðapp JavaScript API.
See https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console.
This command allows to open a console on a running geth node.

ETHEREUM OPTIONS:
  --datadir "/root/.ethereum"  Data directory for the databases and keystore

API AND CONSOLE OPTIONS:
  --jspath loadScript  JavaScript root path for loadScript (default: ".")
  --exec value         Execute JavaScript statement
  --preload value      Comma separated list of JavaScript files to preload into the console

WARN [07-28|14:12:36.162] Sanitizing cache to Go's GC limits       provided=1024 updated=331
flag provided but not defined: -format
```

**Comment by Sonblind** [comment]
I needed to be in the project directory. Here is the output: 
```
Template parsing error: template: :1:2: executing "" at <index .NetworkSettin...>: error calling index: index of nil pointer
WARN [07-28|14:19:02.884] Sanitizing cache to Go's GC limits       provided=1024 updated=331
Fatal: Failed to start the JavaScript console: api modules: 403 Forbidden invalid host specified

Fatal: Failed to start the JavaScript console: api modules: 403 Forbidden invalid host specified
```

**Comment by javahippie** [comment]
Did you execute the whole statement from inside the container or on your Mac? There are expressions in there to look up the container ID and IP addresses, the error message indicated that these lookups did not work. If this script won't work from your Mac, maybe try this one from inside the miner-1 container, working directory "/opt":

`./geth attach http://172.25.0.104:8545`

**Comment by Sonblind** [comment]
I ran that from my mac, which through the errors you see above. `./geth attach http://172.25.0.104:8545` works from within miner1

**Comment by javahippie** [comment]
Do you have any issue connecting to internal docker networks of different configurations? To me it seems like the network is running fine, but you are not able to access it from your computer. How did you install Docker? 

Somebody contacted me and told me, that he can only connect to the network if he executes `sudo docker-compose up`, otherwise they had the same problem as you. Does this work?

**Comment by Sonblind** [comment]
@javahippie Everything works with `sudo`. I installed docker for mac. I will try again with `docker-machine` and give that a shot. Thanks for the help~

**Comment by javahippie** [comment]
Since this seems to be a Docker issue and not an issue with the images, I am closing the issue.
